"use client";

import { useEffect, useState } from "react";
import { useRouter, useParams } from "next/navigation";
import Navbar from "@/components/Navbar";
import { useAuth } from "@/lib/auth-context";
import {
  getLecture,
  updateLecture,
  Lecture,
} from "@/lib/firestore-helpers";

interface Step {
  id: string;
  label: string;
  duration: number; // milliseconds
}

const STEPS: Step[] = [
  { id: "upload", label: "Uploading audio file", duration: 1200 },
  { id: "transcribe", label: "Transcribing speech (Whisper)", duration: 3500 },
  { id: "analyze", label: "Analyzing concepts & structure", duration: 2000 },
  { id: "summary", label: "Generating summary", duration: 2500 },
  { id: "quiz", label: "Creating quiz questions", duration: 2000 },
  { id: "flashcards", label: "Building flashcards", duration: 1800 },
];

export default function ProcessingPage() {
  const { user, loading } = useAuth();
  const router = useRouter();
  const params = useParams();
  const lectureId = params.id as string;

  const [lecture, setLecture] = useState<Lecture | null>(null);
  const [currentStepIdx, setCurrentStepIdx] = useState(0);
  const [completedSteps, setCompletedSteps] = useState<Set<string>>(new Set());
  const [stepTimings, setStepTimings] = useState<Record<string, number>>({});
  const [done, setDone] = useState(false);
  const [error, setError] = useState("");

  // Protect route
  useEffect(() => {
    if (!loading && !user) router.push("/signin");
  }, [user, loading, router]);

  // Load lecture & verify
  useEffect(() => {
    if (!user || !lectureId) return;
    (async () => {
      try {
        const data = await getLecture(lectureId);
        if (!data) {
          setError("Lecture not found");
          return;
        }
        if (data.userId !== user.uid) {
          router.push("/dashboard");
          return;
        }
        // If already ready, skip to lecture page
        if (data.status === "ready") {
          router.push(`/lecture/${lectureId}`);
          return;
        }
        setLecture(data);
      } catch (err) {
        console.error(err);
        setError("Failed to load lecture");
      }
    })();
  }, [user, lectureId, router]);

  // Run the pipeline simulation
  useEffect(() => {
    if (!lecture || done || error) return;

    let cancelled = false;
    let totalElapsed = 0;

    const runPipeline = async () => {
      for (let i = 0; i < STEPS.length; i++) {
        if (cancelled) return;
        const step = STEPS[i];
        setCurrentStepIdx(i);

        const start = Date.now();
        await new Promise((resolve) => setTimeout(resolve, step.duration));
        if (cancelled) return;

        totalElapsed += Date.now() - start;
        setCompletedSteps((prev) => new Set(prev).add(step.id));
        setStepTimings((prev) => ({ ...prev, [step.id]: totalElapsed }));
      }

      // ============ MOCK DATA ============
      // TODO: زميلك سيستبدل هذا بالـ AI الحقيقي (Whisper + GPT)
      try {
        await updateLecture(lectureId, {
          status: "ready",
          duration: 3600, // 60 minutes (placeholder)
          transcript: [
            {
              time: "00:00",
              text: "هذا نص تجريبي للمحاضرة سيتم استبداله بالتفريغ الفعلي من Whisper API",
            },
            {
              time: "00:24",
              text: "This is sample transcript text that will be replaced with actual Whisper API output.",
            },
            {
              time: "01:15",
              text: "محتوى تجريبي للعرض حتى يتم ربط AI من قبل الزميل.",
            },
          ],
          summary: {
            objectives: [
              "Sample learning objective 1 — will be replaced by GPT",
              "Sample learning objective 2",
              "Sample learning objective 3",
            ],
            concepts: [
              {
                term: "Sample Concept",
                definition:
                  "This is a placeholder concept that will be generated by GPT-4o-mini.",
              },
              {
                term: "Another Concept",
                definition: "Placeholder definition for demonstration.",
              },
            ],
            emphasized: [
              {
                title: "Sample emphasis",
                content:
                  "This is what the professor would have emphasized — generated by AI.",
              },
            ],
            examples: [
              "Sample worked example that will be extracted by AI from the lecture.",
            ],
          },
          quiz: [
            {
              id: "q1",
              type: "mcq",
              question: "This is a sample question. Real questions will be generated by GPT.",
              choices: ["Option A", "Option B (correct)", "Option C", "Option D"],
              correctAnswer: "Option B (correct)",
              explanation: "This explanation will be AI-generated based on lecture content.",
              timestamp: "00:24",
            },
          ],
          flashcards: [
            {
              id: "fc1",
              front: "What is a sample concept?",
              back: "A placeholder until AI integration is complete.",
              difficulty: null,
            },
          ],
        });

        if (!cancelled) {
          setDone(true);
          // Wait 1 second so user sees completion, then redirect
          setTimeout(() => {
            router.push(`/lecture/${lectureId}`);
          }, 1500);
        }
      } catch (err: any) {
        console.error(err);
        if (!cancelled) setError(err.message || "Processing failed");
      }
    };

    runPipeline();

    return () => {
      cancelled = true;
    };
  }, [lecture, lectureId, router, done, error]);

  const formatTime = (ms: number) => {
    const sec = Math.floor(ms / 1000);
    const mins = Math.floor(sec / 60);
    const secs = sec % 60;
    return `${mins}:${String(secs).padStart(2, "0")}`;
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="font-mono text-sm text-ink-mute">Loading…</div>
      </div>
    );
  }

  if (error) {
    return (
      <>
        <Navbar />
        <div className="pt-20 min-h-screen flex items-center justify-center">
          <div className="text-center max-w-md px-6">
            <div className="text-6xl mb-6">⚠️</div>
            <h1 className="font-serif text-3xl font-medium mb-3">
              Processing failed
            </h1>
            <p className="text-ink-soft mb-8">{error}</p>
            <button
              onClick={() => router.push("/dashboard")}
              className="bg-ink text-paper px-6 py-3 rounded-full text-sm font-medium hover:bg-accent transition"
            >
              ← Back to Dashboard
            </button>
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <Navbar />

      <main className="pt-20 min-h-screen flex items-center justify-center px-6">
        <div className="max-w-2xl w-full py-12 text-center">
          {/* Spinning ring with "m" */}
          <div className="w-32 h-32 mx-auto mb-10 relative">
            <div
              className={`w-32 h-32 border-[3px] rounded-full ${
                done
                  ? "border-sage"
                  : "border-bg-alt border-t-accent animate-spin-slow"
              }`}
            ></div>
            <div className="absolute inset-0 flex items-center justify-center font-serif italic text-6xl text-accent">
              {done ? "✓" : "m"}
            </div>
          </div>

          <h1 className="font-serif text-3xl md:text-4xl font-medium mb-3 tracking-tight">
            {done ? "All done!" : "Working on your lecture…"}
          </h1>

          <p className="text-ink-soft mb-10">
            {done
              ? "Redirecting to your lecture page…"
              : `Processing "${lecture?.title || "lecture"}". This may take 1–3 minutes.`}
          </p>

          {/* Pipeline steps */}
          <div className="bg-paper border border-line rounded-3xl p-6 md:p-8 text-left">
            {STEPS.map((step, i) => {
              const isDone = completedSteps.has(step.id);
              const isActive = i === currentStepIdx && !isDone && !done;
              const isPending = i > currentStepIdx && !done;

              return (
                <div
                  key={step.id}
                  className={`flex items-center gap-4 py-3.5 ${
                    i < STEPS.length - 1 ? "border-b border-line" : ""
                  } ${isPending ? "opacity-40" : "opacity-100"}`}
                >
                  <div
                    className={`w-9 h-9 rounded-full flex items-center justify-center font-mono text-xs font-semibold flex-shrink-0 transition-all ${
                      isDone
                        ? "bg-sage text-paper"
                        : isActive
                        ? "bg-accent text-paper animate-pulse-soft"
                        : "bg-bg-alt text-ink-soft"
                    }`}
                  >
                    {isDone ? "✓" : i + 1}
                  </div>
                  <div className="flex-1 text-sm font-medium">
                    {step.label}
                  </div>
                  <div className="font-mono text-[11px] text-ink-mute flex-shrink-0">
                    {isDone
                      ? formatTime(stepTimings[step.id] || 0)
                      : isActive
                      ? "in progress…"
                      : "queued"}
                  </div>
                </div>
              );
            })}
          </div>

          <p className="text-xs text-ink-mute mt-6 font-mono">
            You can safely close this tab — processing continues in the
            background.
          </p>
        </div>
      </main>
    </>
  );
}